function llhplot(Y1)
%CREATEFIGURE(Y1)
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 18-Jan-2010 12:53:33

% Create figure
figure1 = figure('PaperSize',[20.98 29.68],'Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1,'YScale','log','YMinorTick','on','LineWidth',1,'FontSize',14);
box(axes1,'on');
hold(axes1,'all');

% Create plot
plot(Y1,'LineWidth',2,'Color',[0 0 0]);

% Create xlabel
xlabel({'M parameter'},'LineWidth',2,'FontSize',14);

% Create ylabel
ylabel({'absolute error in log likelihood'},'LineWidth',2,...
    'FontSize',14);

