function scatterplot(X1, Y1)
%CREATEFIGURE(X1,Y1,S1,C1)
%  X1:  scatter x
%  Y1:  scatter y
%  S1:  scatter s
%  C1:  scatter c

%  Auto-generated by MATLAB on 18-Jan-2010 12:20:04

% Create figure
figure1 = figure('Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1,'YScale','log','YMinorTick','on','LineWidth',1,...
    'FontSize',14);

% Uncomment the following line to preserve the X-limits of the axes
xlim(axes1,[-28 0]);
% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes1,[1e-12 1.5e1]);
box(axes1,'on');
hold(axes1,'all');

% Create scatter
scatter(X1,Y1,'MarkerFaceColor',[0 0 0],'MarkerEdgeColor',[0 0 0],...
    'Marker','.');

% Create xlabel
xlabel('log probability density','LineWidth',2,'FontSize',14);

% Create ylabel
ylabel('absolute error','LineWidth',2,'FontSize',14);




